imageCredentials:
  registry: docker.com
  #pullSecrets: docker-registry-secrets
  # username: docker_user
  # password: docker_user_password
# docker image for master and slaves
images:
  master:
    repo: cloudhero/jmeter-master
    tag: latest
    pullPolicy: Always
  slave:
    repo: cloudhero/jmeter-slave
    tag: latest
    pullPolicy: Always

annotations: {}

config:
  disableSSL: true
  master:
    #testsConfigMap: jmeter-test
    replicaCount: 1
    restartPolicy: Always
    oneShotTest: false
  slaves:
    replicaCount: 2
    restartPolicy: Always

labels: {}

influxdb:
  enabled: false

grafana:
  enabled: false

